spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"

  cassandra:
    keyspace-name: device_configuration
    port: 9042
    schema-action: none
    local-datacenter: datacenter1

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development

  cassandra:
    contact-points: localhost
    username: cassandra
    password: password

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker

  cassandra:
    contact-points: cassandra
    username: cassandra
    password: password

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
